qcacld-3.0: reverse fw-provided mac addr
* When wlan_mac.bin is missing for whatever reason, qcacld will fall
  back to loading mac address from firmware. The OnePlus firmware can
  provide a correct mac address, but it is in reverse, breaking the
  qcacld logic.
* Just reverse it back in qcacld. Although wlan_mac.bin should not be
  missing at all, we have seen some rare cases where it could not be
  generated properly for some reason, and the qcacld fallback is broken
  because of byte-ordering. Let's at least make the fallback path work.

[Adam W. Willis]:
* Fix compilation error not only on GCC, but current LLVM toolchains as
well:

../drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_main.c:11006:7: error: GCC does not allow variable declarations in for loop initializers before C99 [-Werror,-Wgcc-compat]
        for (int i = 0; i < len / 2; i++) {

Co-authored-by: Adam W. Willis <return.of.octobot@gmail.com>
Signed-off-by: Abhay Singh Gill <abhaygill017@gmail.com>